### ISSUE TITLE
Too much file headers? Beautify source codes?

### ISSUE THREAD

**Issue by grikomsn** [devitapp-codes/collab-test#1]
Sampai commit terakhir (a2e1e18d8bf020601163574935286dd14c86ce59), masih banyak source code yang belum rapi dan ada beberapa source code yang menggunakan file header yang banyak.

Example:
https://github.com/devitapp-codes/collab-test/blob/master/Mini_Games/TypeFastGame.cpp

**Comment by dewnan98** [comment]
Memang hidupku gk pernah rapih haha,,😂 ,, iya masih belajar biar bisa buat code simpel dan mudah dibaca oleh programmer lain,, write the beauty code, need time and more practice. Itu programnya asalasalan,  gk di desain dulu sperti apa,, langsung ngoding haha,, jdi tak pake semua header dan kawankawan😂,,, banyak yg gk terpakai sih,,😅

**Comment by grikomsn** [comment]
IDE nya pakai CodeBlocks, lansung pakai plugin yang buat merapikan source code kan bisa (AStyle atau apa namanya). Untuk file header, pakai salah satu tapi jangan dua-duanya (`string` atau `string.h`).

**Comment by grikomsn** [comment]
Fixed on ce80a480bdd7416931c4918eeb228f1a743bce4d, thanks @dewnan98!

**Comment by grikomsn** [comment]
Fixed on ce80a480bdd7416931c4918eeb228f1a743bce4d, thanks @dewnan98! 😄

**Comment by dewnan98** [comment]
Memang hidupku gk pernah rapih haha,,😂 ,, iya masih belajar biar bisa buat code simpel dan mudah dibaca oleh programmer lain,, write the beauty code, need time and more practice. Itu programnya asalasalan,  gk di desain dulu sperti apa,, langsung ngoding haha,, jdi tak pake semua header dan kawankawan😂,,, banyak yg gk terpakai sih,,😅
